name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm ci
      - run: npm test

      - name: Command that outputs stdout and stderr
        uses: ./
        id: both
        continue-on-error: true
        with:
          run: node -e "console.log('foo');console.error('bar')"
      - name: Assert stdout
        if: "${{ steps.both.outputs.stdout != 'foo\n' }}"
        run: exit 1
      - name: Assert stderr
        if: "${{ steps.both.outputs.stderr != 'bar\n' }}"
        run: exit 1

      - name: Test multiline command with environment variable
        uses: ./
        id: multi
        env:
          HELLO: Hello
        with:
          run: |
            echo $HELLO
            echo world!
      - name: Assert stdout
        if: "${{ steps.multi.outputs.stdout != 'Hello\nworld!\n' }}"
        run: exit 1
      - name: Assert stderr
        if: "${{ steps.multi.outputs.stderr != '' }}"
        run: exit 1

      - name: Test unknown shell
        uses: ./
        continue-on-error: true
        id: unknown-shell
        with:
          run: ls -al
          shell: unknown
      - name: Should fail on unknown shell
        if: ${{ steps.unknown-shell.outcome != 'failure' }}
        run: exit 1

      - name: Test timeout
        uses: ./
        continue-on-error: true
        id: timeout
        with:
          run: |
            echo "sleeping for 30s"
            sleep 30
          shell: bash
          no_output_timeout: 1
      - name: Should fail
        if: ${{ steps.timeout.outcome != 'failure' }}
        run: exit 1
